### ISSUE TITLE
full report is down

### ISSUE THREAD

**Issue by yifuguo** [aehaynes/reddit_authorship#1]
wayback machine nor google cache has a copy.

would be nice for you to upload it somewhere else for historical purpose.

thanks!

**Comment by aehaynes** [comment]
Hi there,

The full report is still up for me. You can find another copy of it here vixra.org/pdf/1507.0145v1.pdf

**Comment by yifuguo** [comment]
Ah I was talking about andrehaynes.me/portfolio 

if the PDF contains all the information that's fine, there's a couple of mirrors of it and I managed to grab it.

**Comment by aehaynes** [comment]
Yeah, the pdf is the "full" report. I release it is a bit short on technical details but feel free to message me if you have any questions.

**Comment by nshCore** [comment]
I question the validity of this data anyway my handle appears in there and I have one account. Do you just look for people who reply to each other?

**Comment by aehaynes** [comment]
> I question the validity of this data anyway my handle appears in there and I have one account. Do you just look for people who reply to each other?

No, the dataset included all comments and threads in r/bitcoin from 2014 til June 2015. You can download the full dataset used and assess it's validity for yourself here https://www.dropbox.com/s/sn64yu46kr5z1m9/redditDB.sqlite?dl=0
